# -*- makefile -*-

default_CONFIG  = CONFIG_APP_SHV_FWUPDATER=x

ifeq ($(CONFIG_APP_SHV_FWUPDATER),y)

LOCAL_CONFIG_H = appl_config.h

#INCLUDES += -I$(USER_INCLUDE_DIR)/ul_lib -I.

INCLUDES += -I.

bin_PROGRAMS = shv_fwupdater

shv_fwupdater_SOURCES  = appl_main.c appl_shv.c

shv_fwupdater_PROGBUILTIN = all
shv_fwupdater_PROGBUILTIN_EXCLUDE = module ice_v_pmsm

lib_LOADLIBES += shvtree ulevpoll ulut
ifeq ($(firstword $(OMK_RULES_TYPE)),nuttx)
lib_LOADLIBES += system_opt
else
lib_LOADLIBES += rt
lib_LOADLIBES += pthread
lib_LOADLIBES += m
endif

endif #CONFIG_APP_MZ_APO_2DC_T1
